### ISSUE TITLE
Чтобы добавить?

### ISSUE THREAD

**Issue by InfiniteCore** [InfiniteCore/discord-nitro-bot#1]
Друзья!Я сделал бота , который чекает нитро , чтобы добавить?
Есть преположения кидания нитра в лс , а не в гильдию , но не знаю сделаю или нет :D

**Comment by MineFortW** [comment]
Тебя взломали в ДС? Я МС дос с шилд хост

**Comment by InfiniteCore** [comment]
Не знаю , у меня 2 FA

**Comment by InfiniteCore** [comment]
Наверно с компа онлайн , просто я там иногда оставляю

**Comment by MineFortW** [comment]
> Не знаю , у меня 2 FA

Просто сказали тебя и Deserve взломал какой-то Энтони и удалили вас с ДС сервера
